---
title: Data Cleaning
format: typst
---

```{r}
library(tidyverse)

# Load the precinct-level dataset
votes_precinct <- read_csv("data/g24_sov_by_g24_svprec.csv")
head(votes_precinct)
```

```{r}
votes_precinct <- votes_precinct |>
    mutate(
        # Remove spaces at the beginning/end of text entries
        across(where(is.character), str_trim),
        # Convert all text to uppercase 
        across(where(is.character), str_to_upper),
        # Remove any double spaces within text 
        across(where(is.character), str_squish),
        # Replace masked values *** with NA
        across(where(is.character), ~ na_if(.x, "***")))

#Convert key columns to the correct data type
votes_precinct <- votes_precinct |>  
    mutate(COUNTY = as.integer(COUNTY),
           FIPS = as.character(FIPS),
           CDDIST = as.integer(CDDIST),
           SDDIST = as.integer(SDDIST),
           BEDIST = as.integer(BEDIST),
           TOTREG = as.numeric(TOTREG))

# Each precinct should have a unique SVPREC_KEY. If duplicates exist, only keep the first record.
sum(duplicated(votes_precinct$SVPREC_KEY))
votes_precinct <- votes_precinct |> distinct(SVPREC_KEY, .keep_all = TRUE)

write_csv(votes_precinct, "data/g24_sov_by_g24_svprec_clean.csv")
votes_precinct
```

**Note**: According to the Statewide Database disclaimers, some precincts have fewer than ten voters and are masked for privacy, so certain vote count fields are recorded as 0 or \*\*\*. These were replaced with NA where appropriate. A few 0s are normal and expected in uncontested races or small precincts.

```{r}
View(votes_precinct)
```

**Section 2:**

```{r}
library(sf)
sr_shp <- st_read("data/shapefiles/srprec_state_g24_v01_shp.shp")

sr_shp <- sr_shp |>
    st_transform(3310) |>          
    st_set_precision(1) |>         
    st_make_valid() |>            
    st_collection_extract("POLYGON")  
```

```{r}
cd_ab604 <- st_read("data/shapefiles/AB604.shp") |>
    st_transform(3310)
```

```{r}
sr_votes <- read_csv("data/state_g24_sov_data_by_g24_srprec.csv")
```

```{r}
sr_data <- left_join(sr_shp, sr_votes, by = c("SRPREC_KEY" = "SRPREC_KEY"))
```

```{r}
reallocated_DEM <- st_interpolate_aw(sr_data["DEMREG"], cd_ab604, extensive = TRUE)
reallocated_REP <- st_interpolate_aw(sr_data["REPREG"], cd_ab604, extensive = TRUE)

cd_ab604$DEM <- reallocated_DEM$DEMREG
cd_ab604$REP <- reallocated_REP$REPREG

cd_ab604 <- cd_ab604 |> mutate(TOTAL = DEM + REP, WINNER = if_else(DEM > REP, "DEM", "REP"))

head(cd_ab604)
```

```{r}
ggplot(cd_ab604) +
    geom_sf(aes(fill = WINNER), color = NA) +
    scale_fill_manual(values = c("DEM" = "blue", "REP" = "red")) +
    labs(title = "2024 Election Re-run under AB604 Districts", fill = "Winning Party")
```
